version: "3.7"

services:
  gatekeeper:
    container_name: gatekeeper
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: node ./dist/src/main.js
    depends_on:
      - gatekeeper_db
    networks:
      - gatekeeper
  gatekeeper_db:
    image: postgres:12-alpine
    container_name: gatekeeper_db
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    networks:
      - gatekeeper
    restart: unless-stopped

networks:
  gatekeeper:
