name: node

on:
  push:
    branches:
      - master
      - actions-deploy

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Copy configuration files
      run: |
        cp /var/services/gatekeeper/.test-environment .
        cp /var/services/gatekeeper/config.json .
        cp /var/services/gatekeeper/res/adjectives.json ./res
        cp /var/services/gatekeeper/res/nouns.json ./res
    - name: Install dependencies
      run: |
        npm install
    - name: Setup database
      run: |
        source .test-environment
        createdb gatekeeper-test-$GITHUB_SHA-${{ matrix.node-version }}
        export GATEKEEPER_DB_NAM=gatekeeper-test-$GITHUB_SHA-${{ matrix.node-version }}
        npm run upgrade
    - name: Build
      run: |
        npm run build
    - name: test
      run: |
        npm run test
    - name: Destroy database
      run: |
        dropdb gatekeeper-test-$GITHUB_SHA-${{ matrix.node-version }}
