name: node

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Copy configuration files
      run: |
        cp /var/services/gatekeeper/config.json .
        cp /var/services/gatekeeper/res/adjectives.json ./res
        cp /var/services/gatekeeper/res/nouns.json ./res
    - name: Install dependencies
      run: |
        npm install
    - name: Setup database
      run: |
        createdb gatekeeper-test-$GITHUB_SHA-${{ matrix.node-version }}
        export GATEKEEPER_DB_NAM=gatekeeper-test-$GITHUB_SHA-${{ matrix.node-version }}
        npm run upgrade
      env:
        GATEKEEPER_DB_USR: ${{ secrets.GATEKEEPER_DB_USR }}
        GATEKEEPER_DB_PWD: ${{ secrets.GATEKEEPER_DB_PWD }}
    - name: Build
      run: |
        npm run build
      env:
        GATEKEEPER_DISCORD_TOKEN: ${{ secrets.GATEKEEPER_DISCORD_TOKEN }}
    - name: Test
      run: |
        npm run test
    - name: Destroy database
      run: |
        dropdb gatekeeper-test-$GITHUB_SHA-${{ matrix.node-version }}
      env:
        GATEKEEPER_DB_USR: ${{ secrets.GATEKEEPER_DB_USR }}
        GATEKEEPER_DB_PWD: ${{ secrets.GATEKEEPER_DB_PWD }}
