name: node

on:
  push:
    branches:
      - master
      - actions-deploy

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: database setup
      run: |
        sudo su -m postgres -c 'createdb gatekeeper-test-${{ matrix.node-version }}'
    - name: npm install
      run: |
        npm install
    - name: copy config
      run: |
        cp /var/services/gatekeeper/config.json .
        cp /var/services/gatekeeper/res/adjectives.json ./res
        cp /var/services/gatekeeper/res/nouns.json ./res
    - name: build
      run: |
        npm run build
    - name: test
      run: |
        npm run test
    - name: destroy db
      run: |
        sudo su -m postgres -c 'dropdb gatekeeper-test-${{ matrix.node-version }}''
